Vagrant.configure(2) do |config|
  config.vm.box = 'SaltwaterC/centos-5.1-i386'
  config.vm.hostname = 'ctf01-01'

  config.vm.provider 'virtualbox' do |vb|
    vb.name = 'ctf01-01'
    vb.cpus = 1
    vb.memory = '512'
  end

  config.vm.network 'private_network', ip: '10.10.10.11'

  config.vm.provision 'chef_zero' do |chef|
    chef.version = '12.5.1'
    chef.cookbooks_path = '../../cookbooks'
    chef.add_recipe 'ctf01-01'
  end
end
