<?php
//11/05/2006   11:17:24
$etat['orientation']="P";
$etat['format']="A4";
$etat['footerfont']="helvetica";
$etat['footerattribut']="I";
$etat['footertaille']="8";
$etat['logo']="logopdf.png";
$etat['logoleft']="58";
$etat['logotop']="7";
$etat['titre']="Etat demandé par l'utilisateur [nom] le £aujourdhui";
$etat['titreleft']="41";
$etat['titretop']="36";
$etat['titrelargeur']="130";
$etat['titrehauteur']="10";
$etat['titrefont']="helvetica";
$etat['titreattribut']="B";
$etat['titretaille']="15";
$etat['titrebordure']="0";
$etat['titrealign']="L";
$etat['corps']="Il est proposé ici la présentation de l'etat des utilisateurs (voir utilisateur.etat.inc) avec un sous etat (voir utilisateur1.sousetat.inc)

Ces états sont paramétrables.";
$etat['corpsleft']="7";
$etat['corpstop']="57";
$etat['corpslargeur']="195";
$etat['corpshauteur']="5";
$etat['corpsfont']="helvetica";
$etat['corpsattribut']="";
$etat['corpstaille']="10";
$etat['corpsbordure']="0";
$etat['corpsalign']="J";
$etat['sql']="select nom from utilisateur where Login ='£idx'";
$etat['sousetat']=array("utilisateur1");
$etat['se_font']="helvetica";
$etat['se_margeleft']="8";
$etat['se_margetop']="5";
$etat['se_margeright']="5";
$etat['se_couleurtexte']=array("0","0","0");
?>