<?php
//$Id: allemand.inc,v 1.1 2008-07-24 13:18:52 jbastide Exp $
//*** tab.class.php
$lang['enregistrement']="Registrierung";
$lang['sur']="auf";
$lang['page']="SEITEN";
// *** dbform.class.php
$lang["Supprimer"]="Beseitigen";
$lang["Modifier"]= "Andern";
$lang["Ajouter"]="Hinzufügen";
$lang["de_la"] = "des";
$lang["table"] = "tisches";
$lang["mis_a_jour"]="andere";
$lang["ajoute"]="Fuge hinzu";
$lang["non_enregistre"] = "nein nimm(registriere) auf";
$lang["supprime"] = "beseitigt";
$lang["obligatoire"]= "obligatorisch";
// testverrou
$lang["verrou"]= "tätigen Riegel - die anormale procedure";
?>