<?php
//$Id: anglais.inc,v 1.2 2008-11-13 08:52:18 fraynaud1 Exp $
//*** tab.class.php
$lang['enregistrement']="Recording(s)";
$lang['sur']="to";
$lang['page']="PAGES";
// *** dbform.class.php
$lang["Supprimer"]="Delete";
$lang["Modifier"]= "Modify";
$lang["Ajouter"]="Add";
$lang["de_la"] = "of the";
$lang["table"] = "table";
$lang["mis_a_jour"]="modify";
$lang["ajoute"]="add";
$lang["non_enregistre"] = "Not register";
$lang["supprime"] = "deletes";
$lang["obligatoire"]= "compulsory";
// testverrou
$lang["verrou"]= "active bolt - abnormal procedure";
$lang['mise_a_jour']="update";
$lang["non"]="not";
$lang["effectuee"]="made";
// ***************************
// etat sous etat lettre type
// ***************************
$lang['parametres']='settings';
$lang['generaux']='global';
$lang['mise_en_forme']='shaping';
$lang['du']='of';
$lang['texte']='text';
$lang['titre']='title';
$lang['left']='left';
$lang['top']='top';
$lang['largeur']='width';
$lang['hauteur']='height';
$lang['font']='font';
$lang['taille']='size';
$lang['bordure']='border';
$lang['corps']='body';
$lang['sous_etat']='under state';
$lang['marges']='margins';
$lang['couleur']='color';
$lang['droite']='right';
$lang['haute']='top';
$lang['fond']='back';
$lang['align']='align';
$lang['intervalle']='interval';
$lang['debut']='begining';
$lang['fin']='end';
$lang['entete']='heading';
$lang['tableau']='board';
$lang['flag']='flag';
$lang['orientation']='orientation';
$lang['data']='data';
$lang['numero']='number';
$lang['premier']='first';
$lang['premiere']='first';
$lang['un']='one';
$lang['deux']='two';
$lang['total']='sum';
$lang['cellule']='cell';
$lang['moyenne']='average';
$lang['operations']='operations';
$lang['numerique']='nmeric';
$lang['sql']='sql';
$lang['sousetat']='under state';
$lang['nombre']='number';
$lang['format']='format';
$lang['lettretype']='typifie letter';
?>