<?php
//$Id: espagnol.inc,v 1.1 2008-07-24 13:18:52 jbastide Exp $
//*** tab.class.php
$lang['non_traduit']="Sin traducir";
$lang['enregistrements']="Registro(s)";
$lang['sur']="sobre";
$lang['page']="página";
// *** dbform.class.php
$lang["Supprimer"]="Suprimir";
$lang["Modifier"]= "Modificar";
$lang["Ajouter"]="Anadir";
$lang["de_la"] = "de la";
$lang["table"] = "Tabla";
$lang["mis_a_jour"]="modifica";
$lang["ajoute"]="anade";
$lang["non_enregistre"] = "No registra";
$lang["supprime"] = "suprime";
$lang["obligatoire"]= "obligatorio";
// *** dbformdyn.class.php
$lang['enregistrement']="Registro";
$lang['mise_a_jour']="Actualización";
$lang['non']="no";
$lang['effectuee']="se hace";
// *** txform.class.php
$lang['le']="el";
$lang['fichier']="Archivo";
$lang['est']="es";
$lang['enregistre']="registrado";
//om_lettretype.class.php/om_etat.class.php /om_sousetat.class.php
//commun
$lang["lettretype"] = "Plantilla";
$lang["parametres"]="Parámetros";
$lang["generaux"]="Generales";
$lang["titre"]="Título";
$lang["corps"]="Cuerpo";
$lang["left"]="Left";
$lang["top"]="Top";
$lang["largeur"]="Anchura";
$lang["hauteur"]="Llegadas";
$lang["font"]="Font";
$lang["mise_en_forme"]="El formato";
$lang["du"]="de";
$lang["texte"]="Texto";
$lang["taille"]="Tamaño";
$lang["bordure"]="Frontera";
$lang["align"]="Alineación";
$lang["orientation"]="Orientación";
$lang["format"]="Formato";
$lang["sql"]="SQL";
$lang["portrait"]="retrato";
$lang["paysage"]="paisaje";
$lang["normal"]="normal";
$lang["italique"]="cursiva";
$lang["gras"]="negrita";
$lang["souligne"]="subrayó";
$lang["gauche"]="izquierda";
$lang["droite"]="derecha";
$lang["justifie"]="justificada";
$lang["centre"]="centrada";
$lang["sans"]="sin";
$lang["avec"]="con";
//specifique om_etat.class.php
$lang["choisir"]="Eligir";
$lang["un"]="un";
$lang["etat"] = "Estado";
$lang["sous_etat"] = "Sub Estado";
$lang["marges"] = "Márgenes ";
$lang["haute"] = "Alto";
$lang["couleur"] = "Color";
//specifique om_sousetat.class.php
$lang["transparent"] = "Transparente";
$lang["fond"] = "Fondo";
$lang["entete"] = "Cabecera";
$lang["du"]="de";
$lang["tableau"] = "Tablero";
$lang["data"]="Datos";
$lang["cellule"]="Célula ";
$lang["total"]="Total";
$lang["moyenne"]="Promedio";
$lang["nombre"]="Número";
$lang["operations"]="Operaciones";
$lang["debut"]="Inicio";
$lang["fin"]="Final";
$lang["intervalle"]="Intervalo";
$lang["flag"]="Flag";
$lang["numero"]="Numero";
$lang["un"]="1";
$lang["deux"]="2";
$lang["premiere"]="Primero";
$lang["numerique"]="Digital";
$lang["sousetat"] = "Sub Estado";
// testverrou
$lang["verrou"]= "cerrojo activo - procedure anormal";
?>