<?php
//$Id: francais.inc,v 1.1 2008-07-24 13:18:52 jbastide Exp $
//*** tab.class.php
$lang['non_traduit']="Non Traduit";
$lang['enregistrements']="Enregistrement(s)";
$lang['sur']="sur";
$lang['page']="page";
// *** dbform.class.php
$lang["Supprimer"]="Supprimer";
$lang["Modifier"]= "Modifier";
$lang["Ajouter"]="Ajouter";
$lang["de_la"] = "de la";
$lang["table"] = "Table";
$lang["mis_a_jour"]="mis à jour";
$lang["ajoute"]="ajouté";
$lang["non_enregistre"] = "Non enregistré";
$lang["supprime"] = "supprimé";
$lang["obligatoire"]= "obligatoire";
// *** dbformdyn.class.php
$lang['enregistrement']="Enregistrement";
$lang['mise_a_jour']="mise à jour";
$lang['non']="non";
$lang['effectuee']="effectuée";
// *** txform.class.php
$lang['le']=" Le";
$lang['fichier']="fichier";
$lang['est']="est";
$lang['enregistre']="enregistré";
//om_lettretype.class.php/om_etat.class.php /om_sousetat.class.php
//commun
$lang["lettretype"] = "Lettre Type";
$lang["parametres"]="Parametres";
$lang["generaux"]="Generaux";
$lang["titre"]="Titre";
$lang["corps"]="Corps";
$lang["left"]="Left";
$lang["top"]="Top";
$lang["largeur"]="Largeur";
$lang["hauteur"]="Hauteur";
$lang["font"]="Font";
$lang["mise_en_forme"]="Mise en Forme";
$lang["du"]="du";
$lang["texte"]="Texte";
$lang["taille"]="Taille";
$lang["bordure"]="Bordure";
$lang["align"]="Alignement";
$lang["orientation"]="Orientation";
$lang["format"]="Format";
$lang["sql"]="SQL";
$lang["portrait"]="Portrait";
$lang["paysage"]="paysage";
$lang["normal"]="normal";
$lang["italique"]="Italique";
$lang["gras"]="Gras";
$lang["souligne"]="souligné";
$lang["gauche"]="Gauche";
$lang["droite"]="Droite";
$lang["justifie"]="justifié";
$lang["centre"]="centre";
$lang["sans"]="sans";
$lang["avec"]="avec";
//specifique om_etat.class.php
$lang["choisir"]="Choisir";
$lang["un"]="un";
$lang["etat"] = "Etat";
$lang["sous_etat"] = "Sous Etat";
$lang["marges"] = "Marge ";
$lang["haute"] = "Haute";
$lang["couleur"] = "Couleur";
//specifique om_sousetat.class.php
$lang["transparent"] = "Transparent";
$lang["fond"] = "Fond";
$lang["entete"] = "Entête";
$lang["du"]="du";
$lang["tableau"] = "Tableau";
$lang["data"]="Data";
$lang["cellule"]="Cellule ";
$lang["total"]="Total";
$lang["moyenne"]="Moyenne";
$lang["nombre"]="Nombre";
$lang["operations"]="Operations";
$lang["debut"]="Debut";
$lang["fin"]="Fin";
$lang["intervalle"]="Intervalle";
$lang["flag"]="Flag";
$lang["numero"]="Numero";
$lang["un"]="1";
$lang["deux"]="2";
$lang["premiere"]="Première";
$lang["numerique"]="Numérique";
$lang["sousetat"] = "Sous Etat";
// testverrou
$lang["verrou"]= "Verrou Actif - Procédure anormale";
//*************************//
// ajout (+) juillet 2008  //
//*************************//
$lang["enregistrer"]="Enregistrer";
$lang["identifiant"]="Identifiant";
?>