driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 1024
    nictype1: virtio

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.12.15

platforms:
  - name: ubuntu/precise64
    driver:
      box: ubuntu/precise64

suites:
  - name: ctf01-02
    run_list:
      - recipe[ctf01-02]
    attributes:
      ctf01-02:
        skip_stage_check: true
