driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 1024

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.5.1

platforms:
  - name: SaltwaterC/centos-5.1-i386
    driver:
      box: SaltwaterC/centos-5.1-i386

suites:
  - name: ctf01-01
    run_list:
      - recipe[ctf01-01]
