name 'ctf01-01'
maintainer 'Stefan Rusu'
maintainer_email 'saltwaterc@gmail.com'
license 'MIT'
description 'Installs / Configures ctf01-01'
long_description 'Installs / Configures ctf01-01'
version '0.1.1'
