desc 'Installs runtime dependencies'
task :setup do
  sh 'vagrant plugin install vagrant-omnibus'
  sh 'vagrant plugin install vagrant-berkshelf'
  sh 'vagrant plugin install vagrant-reload'
end

desc 'kitchen converge'
task :default do
  system 'kitchen converge'
end

desc 'kitchen verify'
task :verify do
  system 'kitchen verify'
end

desc 'rubocop'
task :rubocop do
  system 'rubocop -c ../.rubocop.yml'
end

desc 'foodcritic'
task :foodcritic do
  system 'foodcritic .'
end

desc 'kitchen verify && rubocop && foodcritic'
task test: [:default, :verify, :rubocop, :foodcritic]

desc 'kitchen destroy and cleanup'
task :clean do
  system 'kitchen destroy'
  rm_rf '.kitchen'
end
