Vagrant.configure(2) do |config|
  config.vm.box = 'SaltwaterC/ctf01-02'
  config.vm.hostname = 'ctf01-02'

  config.vm.provider 'virtualbox' do |vb|
    vb.name = 'ctf01-02'
    vb.cpus = 2
    vb.memory = 1024
    vb.customize ['modifyvm', :id, '--nictype1', 'virtio']
    vb.customize ['modifyvm', :id, '--nictype2', 'virtio']
  end

  config.vm.network 'private_network', ip: '10.10.10.12'
end
