desc 'Runs "vagrant destroy" and removes .vagrant directory'
task :clean do
  system 'vagrant destroy -f'
  rm_rf '.vagrant'
  rm_f Dir['ctf*.box']
end

desc 'Installs runtime dependencies'
task :setup do
  sh 'vagrant plugin install vagrant-vbguest'
  sh 'vagrant plugin install vagrant-omnibus'
  sh 'vagrant plugin install vagrant-berkshelf'
  sh 'vagrant plugin install vagrant-reload'
end

desc 'Runs "vagrant up"'
task :up do
  system 'vagrant up'
end

desc 'Runs "vagrant provision"'
task :provision do
  system 'vagrant provision'
end

desc 'Runs /opt/implode.sh script to cleanup the box'
task :implode do
  system 'vagrant ssh -c "sudo /opt/implode.sh"'
end

desc 'Packages Vagrant box'
task :package do
  system "vagrant package --output #{$box_name}.box"
end

desc 'Builds a box'
task build: [:clean, :setup, :up, :implode, :package]
