import '../Rakefile'

desc 'Runs "vagrant destroy" and removes .vagrant directory'
task :clean do
  system 'vagrant destroy -f'
  rm_rf '.vagrant'
  rm_f Dir['ctf*.box']
  rm_f Dir['ctf*.json']
end

desc 'Runs "vagrant up"'
task :up do
  system 'vagrant up'
end

desc 'Runs "vagrant provision"'
task :provision do
  system 'vagrant provision'
end

desc 'Runs /opt/implode.sh script to cleanup the box'
task :implode do
  system 'vagrant ssh -c "sudo /opt/implode.sh"'
end

desc 'Packages Vagrant box'
task :package do
  system "vagrant package --output #{$box_name}.box"
end

desc 'Builds a box from scratch'
task build: [:clean, :setup, :up, :implode, :package]

desc 'Builds a development box'
task box: [:up, :implode, :package]
