Vagrant.configure(2) do |config|
  config.vm.box = 'ubuntu/precise64'
  config.vm.hostname = 'ctf01-02'

  config.vm.provider 'virtualbox' do |vb|
    vb.name = 'ctf01-02'
  end

  config.vm.network 'private_network', ip: '10.10.10.12'

  config.omnibus.chef_version = '12.5.1'
  config.vm.provision 'chef_zero' do |chef|
    chef.cookbooks_path = '../../cookbooks'
    chef.add_recipe 'ctf01-02'
  end
end
