Vagrant.require_version '>= 1.8.0'

Vagrant.configure(2) do |config|
  config.vm.box = 'ubuntu/precise64'
  config.vm.hostname = 'ctf01-02'

  config.vm.provider 'virtualbox' do |vb|
    vb.name = 'ctf01-02-image'
    vb.cpus = 2
    vb.memory = 1024
    vb.customize ['modifyvm', :id, '--nictype1', 'virtio']
    vb.customize ['modifyvm', :id, '--nictype2', 'virtio']
  end

  config.vm.network 'private_network', ip: '10.10.10.12'

  config.omnibus.chef_version = '12.12.15'
  config.berkshelf.enabled = true
  config.berkshelf.berksfile_path = '../../cookbooks/ctf01-02/Berksfile'

  config.vm.provision 'chef_zero' do |chef|
    chef.cookbooks_path = '../../cookbooks'
    chef.add_recipe 'ctf01-02::stage1'
    chef.nodes_path = '.'
  end
  config.vm.provision :reload

  config.vm.provision 'chef_zero' do |chef|
    chef.cookbooks_path = '../../cookbooks'
    chef.add_recipe 'ctf01-02::stage2'
    chef.nodes_path = '.'
  end
  config.vm.provision :reload
end
