<?php
//$Id: francais.inc,v 1.15 2008-09-22 09:08:01 jbastide Exp $
$lang['non_traduit']="*";
$lang["langue"] = "&nbsp;Francais&nbsp;";
$lang["title_html"] = "Open Scrutin";
$lang["openmairie"]="Open Mairie";
$lang["site"] ="Site web (Francais)";
$lang["version"] ="Version";
$lang["exemple"] = "Exemple";
$lang["votre_profil_est"] = "Votre profil est";
$lang["vide"]="&nbsp;";
//mois
$lang["Janvier"] ="Janvier";
$lang["Fevrier"] ="Fevrier";
$lang["Mars"] ="Mars";
$lang["Avril"] ="Avril";
$lang["Mai"] ="Mai";
$lang["Juin"] ="Juin";
$lang["Juillet"] ="Juillet";
$lang["Aout"] ="Aout";
$lang["Septembre"] ="Septembre";
$lang["Octobre"] ="Octobre";
$lang["Novembre"] ="Novembre";
$lang["Decembre"] ="Decembre";
//jour Lunes Martes Miércoles Jueves Viernes Sábado Domingo
$lang["Lun"] ="Lun";
$lang["Mar"] ="Mar";
$lang["Mer"] ="Mer";
$lang["Jeu"] ="Jeu";
$lang["Ven"] ="Ven";
$lang["Sam"] ="Sam";
$lang["Dim"] ="Dim";
// date
$lang['date']="Date";
//  ************************************
//  * openmairie surcharge dbform      *
//  ************************************
//
$lang["de_la"] = "de la";
$lang["table"] = "Table";
$lang["mis_a_jour"]="Mis a jour";
$lang["ajoute"]="ajouter";
$lang["non_enregistre"] = "Non Enregistrer";
$lang["supprime"] = "Supprimer";
$lang['enregistrement']="Enregistrement";
//
//  ************************************
//  * tables generique openmairie      *
//  ************************************
//
$lang["collectivite"] = "collectivite";
$lang['maire']="Maire";
$lang['logo']="Logo";
$lang["utilisateur"] = "Utilisateur";
$lang["pwd"]="Mot de Passe";
$lang["idutilisateur"]="Id utilisateur";
$lang["profil"] = "Profil";
$lang["libelle_profil"]="Libelle profil";
$lang["droit"]="Droit";
$lang["droit_acces"] = "Droits d'acces";
$lang["email"] = "Courriel";
// ***************************
// identifiant avec    recherche
$lang['id']="Id<br><img src='../img/rechercher.gif'>";
// identifiant sans recherche
$lang['ids']="Id";
// complement
$lang['cpt']="cpt";
// alt bouton
$lang["retour"]= "Precedente";
$lang["aide"]= "Aide";
// global message
$lang["libelle"]= "libelle";
$lang["obligatoire"]= "obligatoire";
$lang['occurence']="occurrence(s)";
$lang["il_y_a"] = "Il y a";
$lang["pour"] = "pour";
$lang["ou"] = "ou";
$lang["du"]="du";
$lang["votre"]="votre";
$lang["le"]="le";
$lang["la"]="la";
$lang["de"]="de";
$lang["dans"]="dans";
$lang["choisir"] = "Choisir";
$lang["Non"] = "Non";
$lang["Oui"] = "Oui";
$lang["inexistant"]="inexistant";
$lang["existant"]="existant";
$lang["ans"] = "ans";
$lang["incorrect"] = "Incorrect";
$lang["recommencer"] = "Recommencer";
$lang["base"] = "Base de donnes";
$lang["connectee"] = "connectee";
$lang["lancement"]="Lancement";
$lang["vous_n_avez_pas"]="vous n'avez pas";
$lang["suffisants"]="Suffisants";
$lang["insuffisant"]="Insuffisant";
$lang["valider"]="Valider";
$lang["est_valide"]="est valide";
$lang["selection"]="selection";
$lang["en_construction"]="En construction";
$lang["reconnectez_vous"]="Reconnectez_vous";
$lang["pas_de"]="Pas de";
$lang["resultat"]="Resultat";
$lang["pluriel"]="(s)";
$lang["saisie"]="Saisie";
$lang["nouveau"]="Nouveau";
$lang["ancien"]="Ancien";
//commun
$lang['observation']="&nbsp;Observations";
$lang['x']="coordonnee x";
$lang['y']="coordonnee y";
$lang['numero']="Numero";
$lang['plan']="Plan";
$lang['positionnement_sur_plan']="Positionnement sur un plan";
// index.php
$lang['reconnexion_depuis']="Reconnexion depuis";
$lang['choix_bd']="Choix Base de Donnees";
// spg/login.php
$lang["bienvenue"] = "Bienvenue";
$lang["vous_travaillez_sur"] = "Vous travaillez sur ";
$lang["autre_base"] = "Autre Base de Donnees";
$lang["identifiez_vous"]="I D E N T I F I E Z Vous";
$lang["identification"]="Identification";
$lang["acces_a"]="Acces à";
$lang["login"] = "L o g i n ";

//  ******************************************
//  * obj                                    *
//  ******************************************
//fonction verifier -> msg erreur            *
$lang["possible"] ="possible";
$lang["impossible"] ="impossible";
$lang["une_seule"] ="Une Seule";
$lang["un"] ="un";
//fonction  cleSecondaire-> msg erreur       *
$lang["en_lien"] ="En Lien ";
//fonction setonchange ->msg javascript
$lang["saisie_uniquement_numerique"]="Saisie uniquement numerique";
//fonction setlib
$lang["identifiant"] ="Identifiant";
//  ________________________________________
//   obj  metier                          //
// _________________________________________
//* srcutin.class.php
$lang["code"] ="Code";
$lang["NE_DOIT_PAS_COMPORTER_DE_CARACTERE(S)_BLANC"]="NE DOIT PAS COMPORTER DE CARACTERE(S) BLANC";
$lang["1er"] ="1er";
$lang["2eme"] ="2eme";
//* agent.class.php
$lang["l"] ="l ";
//* poste.class.php /periode.class.php
$lang["vous_ne_pouvez_pas_supprimer"]="Vous ne pouvez pas supprimer";
$lang["utilise"]="utilisé";
$lang["n_est_pas_une_heure"]="n est pas une heure";
//* affectation.class
$lang["vous_devez_decider_de_l_affectation_d_un_bureau"]="Vous devez decider de l affectation d un bureau";
$lang["tous_interdit"]="( Tous : INTERDIT )";
$lang["occupe"]="occupé";
$lang["n_est_pas"]="n est pas";
$lang["bureaux"]="bureaux";
$lang["tous"]="tous";
//*candidature.class
$lang["decision_d_affectation_non_prise"]="Decision d affectation non prise";
$lang["depart"]="depart";
$lang["heures_effectuees"]="Heures effectuées";
$lang["horaire"]="horaire";
//  ************************
//  *      scr             *
//  ************************
// requeteur.php
$lang["separateur_champ"]="Separateur de champs ";
$lang["limite"]="Limite";
$lang["sortie"]="Sortie";
$lang["tri"]="Tri";
$lang["donnees"]="données";
$lang["voir"]="Voir";
$lang["resultat"]="Resultat";
$lang["egalement"]="Egalement";
$lang["disponible"]="disponible";
$lang["repertoire"]="Repertoire";
//txtab.php
//txform.php
$lang["texte"]="texte";
//  ************************
//  *           spg        *
//  ************************
//combo et combo2
$lang["verifiez_correspondance_avec"]="Verifiez la correspondance avec";
$lang["aucune_correspondance"]="A u c u n e <br> c o r r e s p o n d a n c e";
$lang["vous_devez_saisir_une_valeur_d_au_moins"]="Vous devez saisir une valeur d au moins";
$lang["caracteres_dans_le_champs"]="caractère(s)<br><br>dans le champs";
// loginchangepwd.php
$lang["deuxieme"]="Deuxieme";
//upload.php
$lang["envoyer"]="E n v o y  e r";
$lang["parcourir"]="Parcourir";
//doc.php
$lang["documentation"]="documentation";
$lang["traduction"]="Traduction";
$lang["en_cours"]="&nbsp;";
$lang["sommaire"]=" S O M M A I R E";
$lang["affectation_r"]="Lettres type Affectation";
$lang["om_lettretype"]="Lettres type (integration OpenMairie)";
$lang["loginchangepwd"]="Mot de Passe";
$lang["om_sousetat"]="Sous Etats (integration OpenMairie)";
$lang["candidature_p"]="Lettre Tyoe Candidature";
$lang["import_script"]="Imports dans la base de données de fichier au format csv téléchargé";
$lang["om_etat"]="Parametrage Etats (integration OpenMairie)";
// voir.php
$lang["fermer"]="Fermer";
$lang['fermer_fenetre']="Fermer cette fenêtre";
//  rvb.php
$lang['palette_graphique']="Palette Graphique";
$lang['composantes_rvb']="Composants RVB";
$lang["rouge"]="R";
$lang["vert"]="V";
$lang["bleu"]="B";
$lang["hexadecimal"]="Hexadecimal";
$lang["couleur"]="Couleur";
$lang["survolee"]="Survolee";
$lang["selectionnee"]="Selectionnee";
$lang["annuler"]="Annuler";
$lang["degrade_de_gris"]="Degrade de gris";
//  ************************
//  *          rec         *
//  ************************
//import_script.php
$lang["upload"]="Upload";
$lang["transfert"]="Transfert";
$lang["fichier"]="Fichier";
$lang["absent"]="Absent";
$lang["a_envoyer"]=" A Envoyer";
//  ************************
//  *   menu haut +msg     *
//  ************************
$lang["recherche_globale"]="Recherche Globale";
$lang["tableau_de_bord"]="Tableau de bord ";
$lang["changer"]="Changer";
$lang["non_accessible_avec"]="&nbsp;non accessible avec";
$lang["mot_de_passe"] = "Mot de Passe";
$lang["deconnexion"] = "(De)Connexion";
$lang["connexion"] = "Connexion";
$lang["vous_n_etes_pas_connecte"] = "vous n'etes pas connecte";
$lang["quitter"]="Quitter";
$lang["documentation"]="Documentation";
//  ************************
//  *   global menu        *
//  ************************
$lang["option"]="option";
$lang["defaut"]="defaut";
$lang["recherche"]="Recherche";
$lang["traitement"]= "Traitement";
$lang["transfert"] = "Transfert";
$lang["edition"] = "Edition";
$lang["import"] ="Import";
$lang["a_propos"] = "A  Propos";
$lang["envoi"] = "Envoi";
$lang["sauvegarde"] = "Sauvegarde";
$lang["lettretype"] = "Lettre Type";
$lang["etat"] = "Etat";
$lang["sous_etat"] = "Sous Etat";
$lang["sousetat"] = "Sous Etat";
$lang["parametrage"] = "Parametrage";
$lang["gestion"] = "gestion";
$lang["requetes_memorisees"]= "Requetes memorisees";
$lang["reqmo"]= "Requetes memorisees";
$lang["message_1"]= "Le fichier a été exporté, vous pouvez l'ouvrir immédiatement en cliquant sur : ";   // ***
$lang["message_2"]="Il est également accessible dans le repertoite tmp, son nom est :";
$lang["afficher_ou_non"]= "Champs à afficher ou non";
$lang["criteres_recherche_tri"]="Critère(s) de recherche et/ou de tri";
$lang["criteres_sortie"]="Critères de sortie";
$lang["archive"]="Archive";
$lang["ergonomie"]="Ergonomie";
//localisation
$lang["plans"] = "Plans";
$lang["zone"]="Zone";
$lang["voie"]="Voie";
//traitement
$lang["libre"]="libre";
//
$lang["localisation"]= "Localisation";
//adresse
$lang["adresse"] = "Adresse";
$lang['adresse1']= "Adresse 1";
$lang['adresse2']="Adresse 2";
$lang['ville']="Ville";
$lang["bis"] = "bis";
$lang["ter"] = "ter";
//zone
$lang['zonetype']= "Type  zone";
$lang['zonelib']= "Libelle zone";
// etat civil
$lang["civilite"]="Civilite";
$lang["mr"] = "Mr";
$lang["mme"] = "Mme";
$lang["melle"] = "Melle";
$lang["nom"] = "Nom";
$lang["marital"] = "Marital";
$lang["prenom"] = "Prenom";
$lang["datenaissance"] = "Date de Naissance";
$lang["etat_civil"] = "Etat Civil";
$lang["cp"] = "Code Postal";
$lang["telephone"] = "Telephone";
//courrier
$lang["courrier"] = "Courrier";
$lang["nocourrier"] = "Numero Courrier";
$lang['destinataire']="Destinataire";
$lang['datecourrier']="Date du Courrier";
$lang['complement']="Complement";
//  ************************************
//  * dyn     *
//  ************************************
// menu.inc
$lang['administration']="Administration";
//  ****************************************************************************
//  *      METIER                                                              *
//  ****************************************************************************
// scrutin
$lang["scrutin_par_defaut"] = "Scrutin par Defaut";
$lang["scrutin"] = "Scrutin";
$lang["SCRUTIN"] = "Scrutin";
$lang["canton"] = "Canton";
$lang["tour"] = "Tour";
$lang["date_scrutin"] = "Date du Scrutin";
$lang["solde"] = "Soldé";
$lang["convocation_agent"] = "Convocation Agent";
$lang["convocation_president"] = "Convocation President";
$lang["candidat"] = "Candidat";
$lang["agent"] = "Agent";
$lang["bureau"] = "Bureau";
$lang["poste"] = "Poste";
$lang["periode"] = "Periode";
$lang["elu"] = "Elu";
$lang["grade"] = "Grade";
$lang["service"] = "Service";
$lang["nomjf"] = "Nom JF";
$lang["date_naissance"] = "Date de Naissance";
$lang["lieu_naissance"] = "Lieu de Naissance";
$lang["nature"] = "Nature";
$lang["ordre"] = "Ordre";
$lang["debut"] = "Debut";
$lang["fin"] = "Fin";
$lang["agent_selection"] = "Selection Agent";
$lang["elu_selection"] = "Selection Elu";
//agent
$lang["decision"] = "Decision";
$lang["candidature"] = "Candidature";
$lang["recuperation"] = "Recuperation";
//elu
$lang["affectation"] = "Affectation";
//bureau
$lang["agent_bureau"] = "Agent";
$lang["elu_bureau"] = "Elu";
//********** EDITION ********************
//Composition bureaux et edition composition
$lang["composition_des_bureaux"]="Composition des bureaux";
$lang["traitement"] = "Traitement";
$lang["de"] = "de";
$lang["creation"] = "Creation";
$lang["selectionnez"] = "Selectionnez";
$lang["confirmation"] = "Confirmation";
$lang["composition"] = "Composition";
$lang["lancez"] = "Lancez";
$lang["ce"] = "ce";
$lang["avant"] = "avant";
$lang["les"] = "les";
$lang["çi_dessous"] = "çi-dessous";
$lang["par"] = "par";
$lang["election"] = "Election";
$lang["president"] = "President";
$lang["suppleant"] = "Suppleant";
$lang["secretaire"] = "Secretaire";
$lang["efface"] = "Effacé";
$lang["cree"] = "crée";
$lang["canton"] = "Canton";
//convocation agents - presidents /recepisse
$lang["publipostage"] = "Publipostage";
$lang["convocation"] = "Convocation";
$lang["des"] = "des";
$lang["lettre"] = "lettre";
$lang["vous"] = "Vous";
$lang["pouvez"] = "pouvez";
$lang["remplir"] = "remplir";
$lang["correspondant"] = "correspondant";
$lang["aux"] = "aux";
$lang["document"] = "document";
$lang["genere"] = "généré";
$lang["recepisse"] = "Récépissé";
$lang["assesseur"] = "Assesseur";
$lang["delegue"] = "Délégué";
$lang["et"] = "et";
//********** TRAITEMENT ********************
//affectation heures
$lang["affectation_automatique_des_heures"]= "Affectation automatique des heures";
$lang["confirmation"] = "Confirmation";
$lang["l_"] = "l\"";
$lang["attention"] = "<img src='../img/warning.gif' style='vertical-align:middle' vspace='2' hspace='2' border='0'>ATTENTION";
$lang["toute"] = "Toute";
$lang["heure"] = "Heure";
$lang["seront_ecrasees"]="seront écrasées";
$lang["candidature"] = "Candidature";
$lang["concernee"] = "Concernée";
$lang["effectuee"] = "éffectuee";
//transfert des candidatures / affectations
$lang["transfert_de_candidatures"]="Transfert de candidatures";
$lang["transfert_des_affectations"]="Transfert des affectations";
$lang["pour_une_election_et_un_poste"]="pour une election et un poste";
$lang["encours"] = "&nbsp;";
$lang["confirmez"] = "Confirmez";
$lang["non"] = "non";
$lang["oui"] = "oui";
$lang["controle"] = "Controlé";
$lang["il_existe"] = "Il existe";
$lang["avec"] = "avec";
//tableau de bord
$lang["choix"] = "CHOIX";
$lang["par_defaut"] = "PAR DEFAUT";
$lang["aucun"] = "AUCUN";
//requeteur
$lang["cpville"] = "Code Postal / Ville";
$lang["TRI"] = "Tri";
$lang["candidat_acceptes"]="Candidats acceptés";
$lang["scrutin_candidat"]="Candidats acceptés";
$lang["etat_des_heures_supplementaires_en_lien_avec_ooo"]="Etat des heures supplementaires en lien avec ooo";
$lang["scrutin_heure"]="Heures supplementaires";
$lang["scrutin_elu"]="Elus";
$lang["elus"]="Elus";
$lang["scrutin_elu_bureau"]="Elus par Bureau";
$lang["elus_bureau"]="Elus par Bureau";
$lang["BUREAU"]="Bureau";
?>