driver:
  name: vagrant
  customize:
    cpus: 1
    memory: 512

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.13.37

platforms:
  - name: ubuntu/precise64
    driver:
      box: ubuntu/precise64

suites:
  - name: ctf02-01
    run_list:
      - recipe[ctf02-01]
