<?php
//$Id: varstyle.inc,v 1.10 2008-09-22 09:08:01 jbastide Exp $
// logo de connexion
$logo_connexion="img/logo.gif";
// Style des boutons
$styleBouton = "font-size:9px;background-color:#4353EF;color:#ffffff;height:22px;border-width:1px;border-color:#000000;";
// style onglet actif
$styleBoutonOnglet = "width:150px;font-size:10px;background-color:#92999D;color:#ffffff;height:23px;font-weight:bold;border-left:solid #ffffff 0px;border-top:solid #ffffff 1px;border-bottom:solid 0px #ffffff;border-right:solid #ffffff 0px";
// style onglet inactif
$styleBoutonOngletInactif = "width:150px;font-size:9px;background-color:#4353EF;color:#ffffff;height:22px;border-width:1px;border-color:white;";
//
$stylebodyupload = "font-size:9px;background-color:#6679EA;color:#ffffff;height:9px;font-weight:bold";
//style lien tdbord
$style_lien_tdb="color:#ffffff;font-size:12px;";
$objet_plan="<img name='CA' src='../img/zoneobligatoire.gif' alt='exemple' border=0 >";
// table fieldset
$style_tablefieldset="font-size:11px;font-weight:normal;background-color:#DBEAFB;color:#000000;width:100%;padding:0px;border: 0px solid #ffffff";
$style_legendfieldset ="background-color:transparent;color:#333399;font-weight:bold;font-size:13px";
$style_fieldset = "background-color:transparent;color:#339999;font-weight:bold;border-color:#6F8DD9";
?>