Vagrant.configure(2) do |config|
  config.vm.box = 'SaltwaterC/ctf01-01'
  config.vm.hostname = 'ctf01-01'

  config.vm.provider 'virtualbox' do |vb|
    vb.name = 'ctf01-01'
    vb.cpus = 1
    vb.memory = '512'
  end

  config.vm.network 'private_network', ip: '10.10.10.11'
end
